### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by bwbroersma** [minvws/nl-covid19-notification-app-dashboard#4]
Shouldn't this dashboard be in English and Dutch? Maybe move to some proper i18n solution?

**Comment by jsoeterbroek** [comment]
My private branch with patch for this issue is called issue #3, but this should be for #4.

**Comment by PaulWagener** [comment]
Fixed with PR https://github.com/minvws/nl-covid19-notification-app-dashboard/pull/12
